### ISSUE TITLE
wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by CountRobel** [kontron/redmine_oauth#2] opened 2022-11-17 16:21 UTC
Hey, thx for the  plugin, working fine! (The Azure AD Login)
With the Receive IMAP example i get following "errors":

ruby/lib/ruby/2.6.0/x64-mingw32/strscan.so: warning: already initialized constant StringScanner::Version
/ruby/lib/ruby/2.6.0/x64-mingw32/strscan.so: warning: already initialized constant StringScanner::Id
wrong number of arguments (given 3, expected 2)

Any Idea?
best regards!

**Comment by picman** [comment] 2022-11-29 09:55
I'd need Redmine and the plugin versions and an exact command you run.

**Comment by CountRobel** [comment] 2022-11-29 10:04
I am using bitnami redmine 5.0.2-2, plugin 2.0.0
Command: C:\Bitnami\redmine-5.0.2-2\apps\redmine\htdocs>bundle exec rake redmine_oauth:email:receive_imap username='O365USERNAME' RAILS_ENV="production"

**Comment by picman** [comment] 2022-11-30 12:55
I can't reproduce the error. However, I work on Linux. Can't you post a bit bigger chunk of the log to see which function call causes wrong number of arguments?

**Comment by CountRobel** [comment] 2022-11-30 13:26
`C:\Bitnami\redmine-5.0.2-2\apps\redmine\htdocs>bundle exec rake redmine_oauth:email:receive_imap username='O365USERNAME' RAILS_ENV="production" --trace
C:/Bitnami/redmine-5.0.2-2/ruby/lib/ruby/2.6.0/x64-mingw32/strscan.so: warning: already initialized constant StringScanner::Version
C:/Bitnami/redmine-5.0.2-2/ruby/lib/ruby/2.6.0/x64-mingw32/strscan.so: warning: already initialized constant StringScanner::Id
** Invoke redmine_oauth:email:receive_imap (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_oauth:email:receive_imap
wrong number of arguments (given 3, expected 2)`

I'll try it on a Linux machine

**Comment by picman** [comment] 2022-12-22 10:46
No feedback => closing.

**Closed by picman** 2022-12-22 10:46 UTC
Labels: bug, wontfix

**Comment by CountRobel** [comment] 2023-01-12 07:19
I've now tried it on Ubuntu and it works great! THX
Do you know what to do so that a new ticket is created if there is no ticket number in the subject of the email?

**Comment by picman** [comment] 2023-01-12 07:33
https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#How-it-works
You have to also define mandatory issue's attributes:
https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Issue-attributes

**Comment by CountRobel** [comment] 2023-01-12 10:32
Thank you!
